
#########################
# DO NOT EDIT THIS FILE #
#########################

# But please, feel free to inspect the targets and design for your own learning.

#
CC := g++
CFLAGS := -Wall -pedantic -g -c -std=c++17
LINKFLAGS := -Wall -pedantic -g -std=c++17


#
BIN_NAME := main
BIN := ./$(BIN_NAME)
#
BIN_SANDBOX_NAME := main-sandbox
BIN_SANDBOX := ./$(BIN_SANDBOX_NAME)
#
BIN_TESTS_NAME := main-tests
BIN_TESTS := ./$(BIN_TESTS_NAME)


#
default:	help


#
help:
	@echo "***** Makefile Menu *****"
	@echo
	@echo "make build         ==> Build source files"
	@echo
	@echo "make run           ==> Run the palindrome detector"
	@echo "make run-sim       ==> Run the palindrome detector with some simulated data"
	@echo "make debug         ==> Debug the palindrome detector with gdb"
	@echo
	@echo "make sandbox       ==> Run the extra sandbox program"
	@echo "make debug-sandbox ==> Debug the extra sandbox program with gdb"
	@echo
	@echo "make test          ==> Run tests against your palindrome detector"
	@echo "make debug-test    ==> Debug the tests run against your palindrome detector"
	@echo
	@echo "make clean         ==> Clean temporary build files"


#
build:	$(BIN) $(BIN_SANDBOX) $(BIN_TESTS)
.PHONY: build


#
run:	$(BIN)
	$(BIN)
.PHONY: run


#
run-sim:	$(BIN)
	@echo "radar\nstoppots\noh dear\nq\n" | $(BIN) `# Pipe to the main program`
.PHONY: run-sim


#
sandbox:	$(BIN_SANDBOX)
	$(BIN_SANDBOX)
.PHONY: sandbox


#
debug-sandbox:	$(BIN_SANDBOX)
	gdb $(BIN_SANDBOX) -ex run
.PHONY: debug-sandbox


#
debug:	$(BIN)
	gdb $(BIN) -ex run
.PHONY: debug


#
gradescope:	test
tests:		test
test:		$(BIN_TESTS)
	$(BIN_TESTS)
.PHONY: gradescope tests test


#
debug-tests:		debug-test
debug-test:	$(BIN_TESTS)
	gdb $(BIN_TESTS) -ex run
.PHONY: debug-tests debug-test


#
$(BIN):	main.o MyDetector.o
	$(CC) $(LINKFLAGS) $^ -o $@


#
$(BIN_SANDBOX):	sandbox.o MyDetector.o
	$(CC) $(LINKFLAGS) $^ -o $@


#
$(BIN_TESTS):	CPP_Tests.o MyDetector.o
	$(CC) $(LINKFLAGS) $^ -o $@


#
main.o:	main.cpp MyDetector.hpp MyQueue.hpp MyStack.hpp
	$(CC) $(CFLAGS) $< -o $@


#
sandbox.o:	sandbox.cpp MyDetector.hpp MyQueue.hpp MyStack.hpp
	$(CC) $(CFLAGS) $< -o $@


#
CPP_Tests.o:	CPP_Tests.cpp MyDetector.hpp MyQueue.hpp MyStack.hpp puhp-tests/*
	$(CC) $(CFLAGS) $< -o $@


#
MyDetector.o:	MyDetector.cpp MyDetector.hpp MyQueue.hpp MyStack.hpp
	$(CC) $(CFLAGS) $< -o $@


#
clean:
	-rm *.o
	-rm $(BIN)
	-rm $(BIN_TESTS)
	-rm $(BIN_SANDBOX)
	-rm results.json
.PHONY: clean









